void	kmc_sleep ();
void	kmc_longsleep ();
char	kmc_wr (int, char[]);
int		kmc_detect_serial_device (int);
void	kmc_clear_serial_buffer (int);
int		kmc_initialize_serial (char *, struct termios *);
void	close_serial_device (int, struct termios *);
int		kmc_get_display_mode (int);
int		kmc_query_display_mode (int);
int		kmc_get_record_ready (int);
void	kmc_query_record_ready (int);
int		kmc_get_setup_mode (int);
void	kmc_query_setup_mode (int);
void	kmc_query_display_status (int);
void	kmc_get_trigger_mode (int, char *);
void	kmc_query_trigger_mode (int);
int		kmc_get_random_mode (int);
void	kmc_query_random_mode (int);
int		kmc_get_rom_version_increase (int);
void	kmc_query_rom_version_increase (int);
int		kmc_get_n_memory_boards (int);
void	kmc_query_n_memory_boards (int);
int		kmc_get_record_rate (int);
void	kmc_query_record_rate (int);
void	kmc_get_display_size (int, char *);
void	kmc_query_display_size (int);
int		kmc_get_shutter_speed (int);
void	kmc_query_shutter_speed (int);
int		kmc_get_playback_rate (int, int);
void	kmc_query_playback_rate (int, int);
void	kmc_serial_full_query (int,int);
void	kmc_press_mode_button (int);
void	kmc_press_record_ready_button (int);
void	kmc_press_trigger_button (int);
void	kmc_press_trigger_button_blocking (int);
void	kmc_press_play_button (int);
void	kmc_press_stop_escape_button (int);
void	kmc_press_up_button (int);
void	kmc_press_menu_enter_button (int);
void	kmc_press_down_button (int);
void	kmc_play (int);
void	kmc_stop (int);
void	kmc_record (int);
void	kmc_move_in_list (int, int);
int		kmc_get_mode (int);
void	kmc_query_mode (int);
void	kmc_set_mode_to_DISPLAY (int);
void	kmc_set_mode_to_LIVE (int);
void	kmc_set_mode_to_RECORD_READY (int);
void	kmc_set_mode_to_DISPLAY_PARAMETERS (int);
void	kmc_set_mode_to_RECORD_PARAMETERS (int);
void	kmc_set_mode_to_RECORD_PARAMETERS_RR (int);
void	kmc_set_shutter_speed (int, int);
void	kmc_set_scsi_id (int, int);
void	kmc_set_display_size (int, char *);
void	kmc_set_trigger_mode (int, char *);
void	kmc_set_record_rate (int, int);
void	kmc_set_play_rate (int, int, int);
void	kmc_trigger_until_live (int);
int		kmc_time_delay_trigger (int, int, int);
void	kmc_test ();

